### ISSUE TITLE
CguZZman's Google Drive addon suddenly causing Kodi to crash

### ISSUE THREAD

**Issue by I-MacHunt** [cguZZman/repository.plugins#13]
Hi,

I have been using cguZZman's Google Drive addon for several years now and apart from an issue where I had to tweak the advancedsettings.xml everything has been working perfectly. That is until a couple of days ago when I went to watch a downloaded show on my Nvidia Shield and after a couple of minutes, Kodi crashed. I thought nothing of it and simply restarted Kodi and tried to resume the show; this time it played for a few seconds and crashed again. Then each subsequent time I'd go back into Kodi, it would crash after approx. 15 - 20 seconds. I systematically began disabling my addons until I got to the last one - Google Drive - and it was only then that Kodi stopped crashing. I have tried clearing caches, uninstalling and reinstalling, tweaking settings but nothing seems to work; each time I re-enable Google Drive, Kodi crashes again within a few seconds. I should also add, that to the best of my knowledge, no updates had been run and I, myself had not (knowingly) changed any settings.

Can you please help?

Many thanks,

Mac.

**Comment by cguZZman** [comment]
Without a debug log file there is nothing I could do

**Comment by I-MacHunt** [comment]
All sorted now thanks. I just did a clean install.
