### ISSUE TITLE
Nexus repo

### ISSUE THREAD

**Issue by petredr** [cguZZman/repository.plugins#17]
Hi,

The google drive addon does not work on Kodi android v20 due to the getfullargspec error..
Its not possible to update to the newest version or connect to the matrix repo as it gives an error.
Would it be possible to have a nexus repo as well? Hopefully will be able to fix this issue soon.
The Kodi nexus repo may have old versions which is why it doesnt work

Thanks

**Comment by janglapuk** [comment]
The update for Kodi Nexus has already been released. Thanks for @cguZZman! 

@petredr, this issue should be able to be closed now.

**Comment by petredr** [comment]
Yes... thanks so much @cguZZman!
