### ISSUE TITLE
Install Google Drive

### ISSUE THREAD

**Issue by shithead01** [cguZZman/repository.plugins#2]
I recently reset my Nvidia Kodi software.  I've got everything back and working just fine, with the exception of Google Drive.  Previously I used the instructions posted by Carlos "cguZZman" and it installed fine and worked well.  This time, I just can't seem to get the installation working at all.  I get to the point the install shows me the 2  preset websites.  Neither of those will connect to the net so I added  my own using the address for Google.com and that did not work either.  I've uninstalled Google drive several times and tried different methods of installation instructions available on the net and yet nothing will actually work.  I installed a different web browser but it does not work very well and this is where I'm stuck

**Comment by cguZZman** [comment]
The installation is like any other addon.
If you still have a problem, tell me step by step what you are doing and may be able to help.

**Comment by cguZZman** [comment]
Closing this issue. If new or more detailed information is submitted, I'll will reopened.

**Comment by shithead01** [comment]
Received your replay, Thanks.  I have not been able to install Google since
doing a factory reset.  Followed you're instructions but get stalled near
the end when trying to connect to Vimeo or the second option.  Added my own
Google website and still get nothing.  Any advice on how to proceed?

**Comment by shithead01** [comment]
Hello Carlos "cguZZman"

Could you please direct me to the correct webpage to start over with
installing Google so I will reset and start over again? Appreciate the help

Bill
