### ISSUE TITLE
local lrc

### ISSUE THREAD

**Issue by houtacheng** [cguZZman/repository.plugins#3]
The lrc lyrics file has the same name as mp3 and is placed in the same googledrive folder, showing that the lyrics cannot be found.

**Comment by cguZZman** [comment]
Lyric files are not supported. I'll mark this as an enhancement. It does not necessarily mean it will be implemented, but just to have it in the list.

**Comment by houtacheng** [comment]
thank you very much

**Comment by cguZZman** [comment]
Also this one.
Can you create the issue in the respective github project. Make sure you enter all required information.
