### ISSUE TITLE
Please upload the latest version of plugin.googledrive to the official repo

### ISSUE THREAD

**Issue by tomyang001** [cguZZman/repository.plugins#5]
The plugin.googledrive in the official Kodi repo is still 1.3.4, which is no longer working. Please upload the latest version, thanks!

**Comment by fabiovieitas** [comment]
Good afternoon friend. The Google drive update worked in parts. However, I can't create STRM files. It always gives error.


"ascii 'codec can't decode byte 0xc3 in position 1 ordinal not in range (128)."

**Comment by cguZZman** [comment]
@tomyang001 the new version is on its way to the kodi repo. It takes time.

@fabiovieitas don't mix unrelated comments to other issues. Create a new issue in the google drive repository. And always, I repeat, always attach your debug log file with all the steps and required information.
