### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HASHOO1** [cguZZman/repository.plugins#7]
hello sir im using google drive for kodi and signin with my google drive account but whenever i try to play some video it start loading for some time and then again back to my videos list with an error message one are more videos failed to play is there any way to fix this issue thanks

**Comment by cguZZman** [comment]
Please create a new issue here: https://github.com/cguZZman/plugin.googledrive/issues with your debug log file attached. Otherwise there is no way to know the problem.
