### ISSUE TITLE
There's an issue with kodi matrix

### ISSUE THREAD

**Issue by hellfish87** [cguZZman/repository.plugins#8]
When i try to install the Google drive addon this give me a error says "failed to install a dependency" what can i do?? This is only no Xbox oneon other devices there's no error

**Comment by bufordt13** [comment]
I also get the "Failed to install a dependency" on a Onn UHD Google TV device, with the latest Kodi Matrix installed.

I was trying to upgrade to the latest version to fix the Matrix Select Streaming format issue.

**Comment by vipulwairagade** [comment]
@cguZZman I also tried to install the latest version 1.4.11 via URL and zip but it always said failed to install. I don't know how do I fix this. I am able to stream with previous version as well, so it's kinda got stuck in between.

**Comment by bufordt13** [comment]
Yes. If you drill down on the add-on you can find the dependencies. Then you can select the Cloud Drive Common module and upgrade it manually. After this, you will be able to upgrade the Google Drive Add-on successfully.

**Comment by cguZZman** [comment]
Without a debug log file there is nothing I could do. There is a new version of the repository. Try with that.
